# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - develop

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: buildServer
        displayName: Build Server
        cancelTimeoutInMinutes: 7
        steps:
          - task: Npm@1
            displayName: "npm ci"
            inputs:
              command: "custom"
              customCommand: "ci"
          - task: Npm@1
            displayName: "npm run test"
            inputs:
              command: "custom"
              customCommand: "run test"
          - task: Npm@1
            displayName: "npm run build"
            inputs:
              command: "custom"
              customCommand: "run build"
          - task: Npm@1
            displayName: "npm prune production"
            inputs:
              command: "custom"
              customCommand: "prune --production"

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              artifact: "server-$(Build.BuildId)"
              publishLocation: "pipeline"

  - stage: deploy
    displayName: Deploy
    dependsOn: build
    jobs:
      - deployment: deployServer
        displayName: Deploy server
        environment: server-dev
        variables:
          - group: server-dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureAppServiceSettings@1
                  displayName: Azure App Service Settings
                  inputs:
                    azureSubscription: "Azure thesis resource manager"
                    appName: "dev-azure-thesis-server"
                    resourceGroupName: "dev-azure-thesis"
                    appSettings: |
                      [
                        {
                          "name": "DB_USER",
                          "value": "$(DB-USER)",
                          "slotSetting": false
                        },
                        {
                          "name": "DB_PASSWORD",
                          "value": "$(DB-PASSWORD)", 
                          "slotSetting": false
                        },
                        {
                          "name": "DB_SERVER",
                          "value": "$(DB-SERVER)", 
                          "slotSetting": false
                        },
                        {
                          "name": "DB_NAME",
                          "value": "$(DB-NAME)", 
                          "slotSetting": false
                        },
                        {
                          "name": "PORT",
                          "value": "8080",
                          "slotSetting": false
                        }
                      ]
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: "AzureRM"
                    azureSubscription: "Azure thesis resource manager"
                    appType: "webAppLinux"
                    WebAppName: "dev-azure-thesis-server"
                    packageForLinux: "$(Pipeline.Workspace)/server-$(Build.BuildId)/*.zip"
                    RuntimeStack: "NODE|12-lts"
                    StartupCommand: "npm start"
                    AppSettings: -PORT "8080"
